### ISSUE TITLE
balanceofsatoshis unable to connect 

### ISSUE THREAD

**Issue by bensig** [mynodebtc/mynode#733]
**Describe the bug**
Unable to use balance of satoshis 

**Expected behavior**
running `bos balance` should connect the same as lncli 

**CLI Output**
```
- 503
- UnexpectedErrorWhenGettingChainBalance
- 
  err: 
    message: 14 UNAVAILABLE: Name resolution failed for target dns:host.docker.internal:10009
```

**MyNode hardware (please complete the following information):**
 - Device: VM
 - Version: 0.3.06
 - BOS Version: 13.10.6

**Additional context**
I'm able to telnet to localhost:10009
bos commands worked fine until recent updates (few weeks ago)

**Comment by bensig** [comment]
Added to /etc/hosts:
`127.0.0.1 host.docker.internal`

Still getting an error:
```
bos balance

- 503
- UnexpectedErrorWhenGettingChainBalance
- 
  err: 
    message: 14 UNAVAILABLE: No connection established
    stack: 
```

checked `bos nodes` 

seeing this error:

```
err: 
  - 400
  - SavedNodeHasInvalidCredentials
```

credentials have not changed since it last worked

```
 cat ~/bos/default/credentials.json 
{
  "cert_path":"/home/
/.lnd/data/chain/bitcoin/mainnet/admin.macaroon"
  "socket": "localhost:10009"
}
```
