### ISSUE TITLE
Deploying new ckpool app in docker

### ISSUE THREAD

**Issue by blacksocket** [mynodebtc/mynode#936]
Dear Support,


I am trying to deploy custom application in docker based on https://github.com/golden-guy/ckpool-solo

Below is the config I a using:

The hardware your are using (Raspberry Pi 4, Rock64, VM, etc...) >>VM in Proxmox
Your current MyNode software version >> 0.3.36

root@mynode:/usr/share/mynode_apps/ckpool# cat docker-compose.yml

```
services:

  ckpool:

    image: gaja77/ckpool-solo:latest

    container_name: ckpool

    restart: unless-stopped

    network_mode: "host"

    volumes:

      - "/usr/share/mynode_apps/ckpool/conf/ckpool.conf:/srv/ckpool/conf/ckpool.conf:ro"

      - "/mnt/hdd/mynode/bitcoin:/srv/ckpool/.bitcoin:ro"

    entrypoint:

      - /srv/ckpool/bin/ckpool      # verify with your new image where the binary lives

      - --config

      - /srv/ckpool/conf/ckpool.conf
```

-------------

root@mynode:/usr/share/mynode_apps/ckpool# cat conf/ckpool.conf

```
{

  "rpchost": "127.0.0.1",

  "rpcport": 8332,

  "rpcuser": "mynode",

  "rpcpassword": "mynode_rpcpassword",

  "btcaddress": "bc1qaddressxxx",

  "stratport": 3333,

  "nodelay": false,

  "stratumdiff": 2,

  "poolnick": "MyNodeSoloPool"

}


  }

}

```
------------

The app is starting properly but for some reason I am Unauthorized:

root@mynode:/usr/share/mynode_apps/ckpool# docker compose up
[+] Running 1/1
 ✔ Container ckpool  Created                                                                                                                                                                                                            0.1s
Attaching to ckpool
ckpool  | [2025-05-13 08:23:20.993] ckpool generator starting
ckpool  | [2025-05-13 08:23:20.993] ckpool stratifier starting
ckpool  | [2025-05-13 08:23:20.993] ckpool connector starting
ckpool  | [2025-05-13 08:23:20.993] ckpool connector ready
ckpool  | [2025-05-13 08:23:21.245] Select timed out in read_socket_line with errno 11: Resource temporarily unavailable
ckpool  | [2025-05-13 08:23:21.245] HTTP response to ( "getblock...) 0.251s not ok: HTTP/1.1 401 Unauthorized
ckpool  | [2025-05-13 08:23:21.245] localhost:8332 Failed to get valid json response to getblocktemplate
ckpool  | [2025-05-13 08:23:21.245] CRITICAL: No bitcoinds active!

---------------------

Strange is that when i use curl it works fine:

root@mynode:/usr/share/mynode_apps/ckpool# curl -s --user mynode:password --data-binary '{"jsonrpc":"1.0","method":"getblockchaininfo","params":[]}' http://127.0.0.1:8332/
{"result":{"chain":"main","blocks":896525,"headers":896525,"bestblockhash":"0000000000000000000004de903c95d8bb9aa5d3d5dfe67affe7d171e7034f6b","difficulty":119116256505723.5,"time":1747123916,"mediantime":1747122184,"verificationprogress":0.9999874263577392,"initialblockdownload":false,"chainwork":"0000000000000000000000000000000000000000c2d2f13b5277849f5dbf25c4","size_on_disk":749442690655,"pruned":false,"warnings":""},"error":null}

Do you know what could be the reason ?
